dias = ("sexta-feira", "sábado", "domingo")
print("Tupla original:")
print(dias)
dias_lista = list(dias)
print("\nTupla convertida para lista:")
print(dias_lista)
dias_lista.append("quarta-feira")
print("\nLista após adicionar um novo dia:")
print(dias_lista)